language:   python
python:
    -   "3.4"
install:
    -   pip3 install -r ./nit-tsuyama/requirements.txt
script:
    -   cd ./nit-tsuyama-old/
    -   python3 calconv.py 2018
    -   cd ../nit-tsuyama/
    -   python3 calconv.py 2018
