version: 2
jobs:
  build:
    # Set Docker image
    docker:
      - image: equanz/calconv

    steps:
      - checkout

      # Install requirements
      - run:
          name: Generate nit-tsuyama Calendar
          command: |
            python -m nit-tsuyama.calconv 2018 csv > ./calendar/nit-tsuyama/index.csv
            python -m nit-tsuyama.calconv 2018 ics > ./calendar/nit-tsuyama/index.ics

      - run:
          name: Push Calendar to Repository
          command: |
            if [ ${CIRCLE_BRANCH} == "add_push_flow" ]; then
              git config --global user.email ${GIT_EMAIL}
              git config --global user.name ${GIT_NAME}
              git add calendar/
              git commit -m "docs: update calendar [ci skip]"
              git push origin ${CIRCLE_BRANCH}
            else
              echo "Pass!"
            fi

workflows:
  version: 2
  cron_workflow:
    triggers:
      - schedule:
          cron: "2 * * * *"
          filters:
            branches:
              only:
                - add_push_flow
    # run build job
    jobs:
      - build
