version: 2
jobs:
  build:
    # Set Docker image
    docker:
      - image: equanz/calconv

    steps:
      - checkout

      # Install requirements
      - run:
          name: Generate nit-tsuyama Calendar
          command: |
            python -m nit-tsuyama.calconv 2018 csv > ./calendar/nit-tsuyama/index.csv
            python -m nit-tsuyama.calconv 2018 ics > ./calendar/nit-tsuyama/index.ics

      - run:
          name: Push Calendar to Repository
          command: |
            # if [ ${CIRCLE_BRANCH} == "master" ]; then
            #   git config --global user.email ${GIT_EMAIL}
            #   git config --global user.name ${GIT_NAME}
            #   git add calendar/
            #   git commit -m "docs: update calendar from CircleCI"
            #   git push ${CIRCLE_REPOSITORY_URL} ${CIRCLE_BRANCH}
            # fi
            git config --global user.email ${GIT_EMAIL}
            git config --global user.name ${GIT_NAME}
            git status
            git pull origin ${CIRCLE_BRANCH}g
            git add calendar/
            git commit -m "docs: update calendar from CircleCI"
            git push origin ${CIRCLE_BRANCH}

