version: 2
jobs:
  build:
    # Set Docker image
    docker:
      - image: equanz/calconv

    steps:
      - checkout

      # Install requirements
      - run:
          name: Generate nit-tsuyama Calendar
          command: |
            python -m nit-tsuyama.calconv 2018 csv
            python -m nit-tsuyama.calconv 2018 ics

